name: Build and Package Extension

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip Extension
      run: |
        mkdir -p build
        zip -r build/bhlwiki_tabs.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name bhlwiki_tabs
        path build/bhlwiki_tabs
