name: Build and Package Extension

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Prepare Build Directory
      run: |
        mkdir -p build
        # Exclude unnecessary files such as .git and other hidden files
        zip -r build/bhlwiki_tabs.zip * -x "*.git*" "build/*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bhlwiki_tabs
        path: build/bhlwiki_tabs.zip
